import bgimg1 from '../images/background img1.jpg'
import coffee1 from '../images/m1.jpg'
import coffee2 from '../images/m2.jpg'
import coffee3 from '../images/m3.jpg'
import coffee4 from '../images/m4.jpg'
import coffee5 from '../images/m5.jpg'
import coffee6 from '../images/m6.jpg'
import coffee7 from '../images/m7.jpg'
import coffee8 from '../images/m8.jpg'
import arabica from '../images/arabica coffee.jpg'
import black from '../images/Black Coffee.jpg'
import Espresso from '../images/Espresso coffee.jpg'
import cappuccino from '../images/Cappuccino coffee.jpg'
import Decaf from '../images/Decaf caffee.jpg'
import Robusta from '../images/Robusta coffee.jpg'
import image7 from '../images/image7.jpg'
import image4 from '../images/image4.jpg'
import image6 from '../images/image6.jpg'
import bgimg2 from '../images/bc3.jpg'
import bgimg3 from '../images/bg-img2.jpg'
import about from '../images/about.jpg'
import homeicon from '../images/home icon.jpg'
import homeabout from '../images/homeabout.jpg'
import hot from '../images/hot-coffees.jpg'
import Cold from '../images/cold-coffees.jpg'
import fraccino from '../images/frappuccino.jpg'
import menu1 from '../images/menu1.jpg'
import menu2 from '../images/menu2.jpg'
import menu3 from '../images/menu3.jpg'
import menu4 from '../images/menu4.jpg'
import menu5 from '../images/PIC5.jpg'
import icon from '../images/icon.jpg'
import icon2 from '../images/icon2.jpg'
import icon3 from '../images/icon3.jpg'
import icon4 from '../images/icon4.jpg'
import icon5 from '../images/services8.jpg'
import icon6 from '../images/services6.jpg'
import icon7 from '../images/serivces8.jpg'
import hotcoffe from '../images/hot-coffees.jpg'
import milkshake from '../images/coffee milk shake.jpg'
import iced from '../images/cold-coffees.jpg'
import cold from '../images/pic4.jpg'
// import iced2  from '../images/icedcofee.jpg'
import hotcoffee from '../images/hotcoff2.jpg'
import milk from '../images/milkshake.jpg'
import gallarybg from '../images/gallarybg.jpg'
import abouthome from '../images/abouthome.jpg'
import serivces8 from '../images/serivces8.jpg'
import serivces9 from '../images/services9.jpg'
import serivces10 from '../images/serivces11.jpg'
import bg10 from '../images/bgimg10.jpg'
import whastapp from '../images/whatsapp.icon.jpg'
import instagram from '../images/instagramicon.jpg'
import facebook from '../images/face.jpg'
import freeshipping from '../images/free shipping.jpg'
import coffebeans from '../images/coffebeans.jpg'
import formbgimg from '../images/formbgimg.jpg'
import login from '../images/loginimg.jpg'
import trans from '../images/trans.jpg'
import signup2 from '../images/sign-up4.jpg'
import insta from '../images/insta-1.jpg'
import face from '../images/face.jpg'
import signin1 from '../images/signup1.jpg'
import iced3 from '../images/icedcoffee.jpg'
import signinlogo from '../images/signin logo.jpg'
import sign1 from '../images/signin-1.jpg'
import insta2 from '../images/insta-1.jpg'
import face1 from '../images/face.jpg'






const data = {
    bgimg1, coffee1, coffee2, coffee3, coffee4, coffee5, coffee6, coffee7, coffee8, arabica, black, Espresso, cappuccino, Decaf, Robusta, image4, image6, image7, bgimg2
    , bgimg3, about, homeicon, homeabout, hot, Cold, fraccino, menu1, menu2, menu3, menu4, menu5, icon, icon2, icon3, icon4, icon5, icon6, icon7
    , hotcoffe, iced, milkshake, login, signin1, iced3, signup2, face, insta, cold, trans, hotcoffee, milk, gallarybg, abouthome, serivces8, serivces9, serivces10, bg10, facebook, whastapp, instagram, freeshipping, coffebeans, formbgimg, sign1,signinlogo,face1,insta2
}
export default data

